import type { TappingScript, TappingRound } from "@/types/tapping";

export interface PreBuiltCategory {
  id: string;
  name: string;
  icon: string;
  color: string;
}

export interface PreBuiltSession {
  id: string;
  categoryId: string;
  title: string;
  description: string;
  durationMinutes: number;
  difficulty: "beginner" | "intermediate" | "advanced";
  script: TappingScript;
}

export const CATEGORIES: PreBuiltCategory[] = [
  { id: "anxiety", name: "Anxiety", icon: "cloud-outline", color: "#6BAFCF" },
  { id: "stress", name: "Stress", icon: "flash-outline", color: "#E8A87C" },
  { id: "sleep", name: "Sleep", icon: "moon-outline", color: "#7C77B9" },
  { id: "confidence", name: "Confidence", icon: "star-outline", color: "#C3A846" },
  { id: "anger", name: "Anger", icon: "flame-outline", color: "#C85A54" },
  { id: "grief", name: "Grief", icon: "heart-outline", color: "#8ECAD6" },
  { id: "addiction", name: "Addiction", icon: "warning-outline", color: "#D4836D" },
  { id: "phobias", name: "Phobias", icon: "eye-off-outline", color: "#9B8EC4" },
  { id: "chronic-pain", name: "Chronic Pain", icon: "fitness-outline", color: "#7BAF8E" },
];

function makeRound(
  num: number,
  type: TappingRound["type"],
  setupStatement: string,
  statements: string[],
  breathing: boolean = false,
  sudCheck: boolean = false
): TappingRound {
  const points = ["KC", "TH", "EB", "SE", "UE", "UN", "CH", "CB", "UA"] as const;
  return {
    roundNumber: num,
    type,
    intensityLevel: type === "setup" ? "high" : type === "positive_reframe" ? "low" : "medium",
    setupStatement,
    tappingPoints: points.slice(0, statements.length).map((point, i) => ({
      point,
      statement: statements[i],
      voiceInstruction: statements[i],
    })),
    breathingPause: breathing,
    sudCheck,
  };
}

export const PRE_BUILT_SESSIONS: PreBuiltSession[] = [
  // Anxiety
  {
    id: "anxiety-quick-calm",
    categoryId: "anxiety",
    title: "Quick Calm",
    description: "A 5-minute session to ease anxious feelings and restore calm.",
    durationMinutes: 5,
    difficulty: "beginner",
    script: {
      sessionId: "anxiety-quick-calm",
      title: "Quick Calm for Anxiety",
      estimatedDurationMinutes: 5,
      rounds: [
        makeRound(1, "setup", "Even though I feel anxious right now, I accept myself as I am.", [
          "Even though I feel this anxiety, I accept myself",
          "This anxiety in my body",
          "I notice this anxious feeling",
          "This worry and tension",
          "All this anxiety I'm feeling",
          "It's okay to feel this way",
          "I acknowledge this anxiety",
          "This anxious feeling in my chest",
          "I'm choosing to let it go",
        ]),
        makeRound(2, "tapping", "I'm releasing this anxiety now.", [
          "Releasing this anxiety",
          "Letting go of worry",
          "My body is calming down",
          "I can breathe through this",
          "Finding peace within myself",
          "I am safe in this moment",
          "Calm is flowing through me",
          "I release what I cannot control",
          "Peace and calm are my natural state",
        ], true),
        makeRound(3, "positive_reframe", "I choose peace and calm.", [
          "I choose peace right now",
          "I am calm and centered",
          "I breathe in peace",
          "My mind is clearing",
          "I feel lighter already",
          "I trust myself to handle this",
          "I am resilient and strong",
          "Peace flows through every cell",
          "I am at ease",
        ]),
      ],
    },
  },
  {
    id: "anxiety-morning-ease",
    categoryId: "anxiety",
    title: "Morning Ease",
    description: "Start your day by releasing anticipatory anxiety.",
    durationMinutes: 7,
    difficulty: "beginner",
    script: {
      sessionId: "anxiety-morning-ease",
      title: "Morning Ease",
      estimatedDurationMinutes: 7,
      rounds: [
        makeRound(1, "setup", "Even though I feel anxious about today, I choose to approach it with calm.", [
          "Even though I'm worried about today",
          "This morning anxiety",
          "Worry about what's ahead",
          "This knot in my stomach",
          "All these what-ifs",
          "This anticipation and dread",
          "I acknowledge these feelings",
          "This anxious energy",
          "I accept where I am right now",
        ]),
        makeRound(2, "tapping", "I am releasing morning anxiety.", [
          "Letting go of this morning worry",
          "I don't need to carry this",
          "Releasing anticipation",
          "I can handle whatever comes",
          "My body is relaxing",
          "Each breath brings more calm",
          "I'm choosing ease this morning",
          "Releasing the need to control today",
          "I'm finding my center",
        ], true, true),
        makeRound(3, "positive_reframe", "Today is going to be a good day.", [
          "I welcome this new day",
          "I am ready for today",
          "Good things are coming",
          "I trust the process of life",
          "I am calm and prepared",
          "Today I choose joy",
          "I am capable and strong",
          "This day is full of possibility",
          "I greet today with open arms",
        ]),
      ],
    },
  },

  // Stress
  {
    id: "stress-release",
    categoryId: "stress",
    title: "Stress Release",
    description: "Let go of accumulated stress and tension in your body.",
    durationMinutes: 6,
    difficulty: "beginner",
    script: {
      sessionId: "stress-release",
      title: "Stress Release",
      estimatedDurationMinutes: 6,
      rounds: [
        makeRound(1, "setup", "Even though I'm feeling stressed, I choose to relax and let go.", [
          "Even though I'm so stressed right now",
          "This stress and overwhelm",
          "My shoulders are tense",
          "This pressure I'm carrying",
          "All this stress in my body",
          "I feel overwhelmed",
          "This weight on my shoulders",
          "All this tension",
          "I accept how I'm feeling",
        ]),
        makeRound(2, "tapping", "I'm choosing to release this stress.", [
          "Letting go of this stress",
          "Releasing tension from my body",
          "My shoulders are dropping",
          "My jaw is unclenching",
          "Stress is leaving my body",
          "I give myself permission to relax",
          "I don't have to carry it all",
          "Releasing this pressure",
          "I am letting go",
        ], true),
        makeRound(3, "positive_reframe", "I am calm, relaxed, and at peace.", [
          "I choose relaxation",
          "My body feels lighter",
          "I am calm and centered",
          "Peace is flowing through me",
          "I handle life with grace",
          "I am more than enough",
          "I feel refreshed and renewed",
          "My mind is clear",
          "I am at peace",
        ]),
      ],
    },
  },

  // Sleep
  {
    id: "sleep-wind-down",
    categoryId: "sleep",
    title: "Wind Down",
    description: "Prepare your mind and body for restful sleep.",
    durationMinutes: 8,
    difficulty: "beginner",
    script: {
      sessionId: "sleep-wind-down",
      title: "Wind Down for Sleep",
      estimatedDurationMinutes: 8,
      rounds: [
        makeRound(1, "setup", "Even though my mind is still active, I give myself permission to rest.", [
          "Even though my mind won't stop",
          "All these thoughts keeping me awake",
          "This restless energy",
          "I can't seem to wind down",
          "My body is tired but my mind is racing",
          "All the things I'm thinking about",
          "This difficulty letting go of the day",
          "I acknowledge my busy mind",
          "I accept where I am right now",
        ]),
        makeRound(2, "tapping", "I'm letting my mind slow down now.", [
          "Letting my thoughts slow down",
          "My mind is getting quieter",
          "I release today's worries",
          "Tomorrow will take care of itself",
          "My body is sinking into comfort",
          "Each breath makes me sleepier",
          "I deserve this rest",
          "My eyelids are getting heavy",
          "Sleep is coming naturally",
        ], true),
        makeRound(3, "positive_reframe", "I drift into peaceful, restorative sleep.", [
          "I am safe and ready to sleep",
          "My body knows how to rest",
          "Deep, peaceful sleep awaits me",
          "I release this day with gratitude",
          "My mind is calm and quiet",
          "Sleep comes easily to me",
          "I drift into peaceful rest",
          "Tomorrow is a fresh start",
          "I am grateful and at peace",
        ]),
      ],
    },
  },

  // Confidence
  {
    id: "confidence-boost",
    categoryId: "confidence",
    title: "Confidence Boost",
    description: "Build self-confidence and overcome self-doubt.",
    durationMinutes: 6,
    difficulty: "intermediate",
    script: {
      sessionId: "confidence-boost",
      title: "Confidence Boost",
      estimatedDurationMinutes: 6,
      rounds: [
        makeRound(1, "setup", "Even though I doubt myself sometimes, I choose to believe in my abilities.", [
          "Even though I doubt myself",
          "This feeling of not being good enough",
          "This self-doubt I carry",
          "Who am I to succeed?",
          "This fear of not measuring up",
          "These critical thoughts about myself",
          "I never feel confident enough",
          "This imposter feeling",
          "I accept all of who I am",
        ]),
        makeRound(2, "tapping", "I am releasing self-doubt.", [
          "Releasing this self-doubt",
          "I don't need to be perfect",
          "I've overcome challenges before",
          "I am capable of great things",
          "Letting go of comparison",
          "My worth is not up for debate",
          "I release the need for approval",
          "I trust my own judgment",
          "I am growing every day",
        ], true),
        makeRound(3, "positive_reframe", "I am confident, capable, and worthy.", [
          "I believe in myself",
          "I am worthy of success",
          "Confidence flows through me",
          "I trust my abilities",
          "I am exactly where I need to be",
          "I radiate confidence",
          "I am proud of who I am",
          "My unique gifts matter",
          "I step forward with courage",
        ]),
      ],
    },
  },

  // Anger
  {
    id: "anger-release",
    categoryId: "anger",
    title: "Anger Release",
    description: "Safely process and release feelings of anger and frustration.",
    durationMinutes: 7,
    difficulty: "intermediate",
    script: {
      sessionId: "anger-release",
      title: "Anger Release",
      estimatedDurationMinutes: 7,
      rounds: [
        makeRound(1, "setup", "Even though I feel this anger, I accept myself and how I feel.", [
          "Even though I'm so angry right now",
          "This burning anger inside me",
          "I feel furious about this situation",
          "This rage I'm holding",
          "It feels like I might explode",
          "This is so unfair",
          "All this anger in my body",
          "I feel it in my fists and jaw",
          "I acknowledge this anger fully",
        ]),
        makeRound(2, "tapping", "I'm choosing to release this anger safely.", [
          "Releasing this anger safely",
          "I can feel angry and still be okay",
          "This anger is trying to protect me",
          "I hear its message",
          "I'm letting the intensity soften",
          "My fists are unclenching",
          "I breathe out the fire",
          "I don't need to hold onto this",
          "I choose to let this pass through me",
        ], true, true),
        makeRound(3, "positive_reframe", "I am calm, strong, and in control.", [
          "I choose peace over anger",
          "I am stronger than my anger",
          "I respond with calm clarity",
          "I release what I cannot change",
          "I am in control of my reactions",
          "I choose understanding",
          "My peace is more important",
          "I feel calmer already",
          "I am at peace with myself",
        ]),
      ],
    },
  },

  // Grief
  {
    id: "grief-gentle-healing",
    categoryId: "grief",
    title: "Gentle Healing",
    description: "A compassionate session for processing grief and loss.",
    durationMinutes: 8,
    difficulty: "intermediate",
    script: {
      sessionId: "grief-gentle-healing",
      title: "Gentle Healing for Grief",
      estimatedDurationMinutes: 8,
      rounds: [
        makeRound(1, "setup", "Even though I feel this deep sadness, I honor my grief and love myself through it.", [
          "Even though I feel this deep loss",
          "This heavy sadness in my heart",
          "I miss what I've lost",
          "This grief feels overwhelming",
          "The emptiness inside me",
          "These waves of sadness",
          "I don't know how to move forward",
          "This pain of loss",
          "I honor these feelings",
        ]),
        makeRound(2, "tapping", "I am allowing myself to grieve and heal.", [
          "Allowing myself to feel this",
          "Grief is a form of love",
          "I don't have to rush healing",
          "I can hold both sadness and love",
          "There is no timeline for grief",
          "I am gentle with myself today",
          "Each tear is healing",
          "I carry love, not just loss",
          "I am not alone in this",
        ], true),
        makeRound(3, "positive_reframe", "I carry love with me as I heal.", [
          "Love remains even through loss",
          "I am healing at my own pace",
          "I honor what I've loved",
          "Gentle strength flows through me",
          "I will smile again",
          "I carry beautiful memories",
          "Healing is happening within me",
          "I am wrapped in love",
          "I move forward carrying love with me",
        ]),
      ],
    },
  },
  // Addiction
  {
    id: "addiction-breaking-free",
    categoryId: "addiction",
    title: "Breaking Free",
    description: "Release the emotional grip of unwanted habits. Best used alongside professional support.",
    durationMinutes: 7,
    difficulty: "intermediate",
    script: {
      sessionId: "addiction-breaking-free",
      title: "Breaking Free from Unwanted Habits",
      estimatedDurationMinutes: 7,
      rounds: [
        makeRound(1, "setup", "Even though I struggle with this habit, I accept myself as I am.", [
          "Even though I feel trapped by this habit",
          "This pull that feels so strong",
          "I feel powerless against it",
          "This cycle I keep repeating",
          "The shame I carry about this",
          "I wish I could just stop",
          "This pattern that controls me",
          "All this frustration with myself",
          "I accept myself despite this struggle",
        ]),
        makeRound(2, "tapping", "I am choosing freedom from this pattern.", [
          "Releasing the grip of this habit",
          "I am more than this pattern",
          "I can choose differently today",
          "Letting go of shame and guilt",
          "I deserve freedom from this",
          "Each moment is a new choice",
          "I am building new pathways",
          "My strength is growing",
          "I am reclaiming my power",
        ], true, true),
        makeRound(3, "positive_reframe", "I am free to choose what serves me.", [
          "I choose what truly serves me",
          "I am stronger than any habit",
          "Freedom flows through me",
          "I trust my ability to change",
          "I am worthy of a healthy life",
          "New patterns are forming",
          "I celebrate every small victory",
          "I am patient with my progress",
          "I am free and getting freer",
        ]),
      ],
    },
  },
  {
    id: "addiction-craving-control",
    categoryId: "addiction",
    title: "Craving Control",
    description: "Manage intense cravings with emotional tapping. Best used alongside professional support.",
    durationMinutes: 6,
    difficulty: "beginner",
    script: {
      sessionId: "addiction-craving-control",
      title: "Craving Control",
      estimatedDurationMinutes: 6,
      rounds: [
        makeRound(1, "setup", "Even though this craving feels overwhelming, I accept myself and this feeling.", [
          "Even though this craving is so intense",
          "This urgent pull I'm feeling",
          "My body is screaming for it",
          "This overwhelming desire",
          "I feel like I can't resist",
          "This tension building inside",
          "The restlessness in my body",
          "This craving that won't let go",
          "I acknowledge this feeling fully",
        ]),
        makeRound(2, "tapping", "I am riding this wave and letting it pass.", [
          "This craving is just a wave",
          "Waves rise and waves fall",
          "I can ride this out",
          "The intensity is already shifting",
          "I don't have to act on this",
          "I am breathing through it",
          "This feeling is temporary",
          "I am safe without giving in",
          "The wave is passing now",
        ], true),
        makeRound(3, "positive_reframe", "I am in control of my choices.", [
          "I am in control right now",
          "I am proud of my resilience",
          "Each craving I ride makes me stronger",
          "I choose peace over impulse",
          "I am capable of this",
          "My willpower is growing",
          "I honor my commitment to change",
          "I feel calmer already",
          "I am free to choose differently",
        ]),
      ],
    },
  },
  {
    id: "addiction-emotional-triggers",
    categoryId: "addiction",
    title: "Emotional Triggers",
    description: "Process the emotions that drive unwanted patterns. Best used alongside professional support.",
    durationMinutes: 8,
    difficulty: "intermediate",
    script: {
      sessionId: "addiction-emotional-triggers",
      title: "Processing Emotional Triggers",
      estimatedDurationMinutes: 8,
      rounds: [
        makeRound(1, "setup", "Even though difficult emotions drive me to old patterns, I accept all parts of myself.", [
          "Even though emotions push me to old habits",
          "When I feel lonely I reach for comfort",
          "When I feel stressed I want to escape",
          "These emotions feel too big to handle",
          "I don't know what else to do with them",
          "This pain underneath the pattern",
          "The feelings I'm trying to avoid",
          "These unmet needs driving my behavior",
          "I accept all these feelings",
        ]),
        makeRound(2, "tapping", "I am learning new ways to process my emotions.", [
          "I can feel emotions without acting out",
          "These feelings are trying to tell me something",
          "I am learning to listen",
          "I don't need to numb or escape",
          "I can sit with discomfort",
          "My emotions are valid and manageable",
          "I am finding healthier ways to cope",
          "Each feeling passes in its own time",
          "I am building emotional resilience",
        ], true, true),
        makeRound(3, "positive_reframe", "I process my emotions with courage and grace.", [
          "I face my emotions with courage",
          "I have healthy ways to cope",
          "My feelings are my guides",
          "I am emotionally resilient",
          "I respond with wisdom, not reaction",
          "I am gentle with myself",
          "I am growing through this",
          "I trust my healing process",
          "I am whole, even in the struggle",
        ]),
      ],
    },
  },

  // Phobias
  {
    id: "phobias-fear-release",
    categoryId: "phobias",
    title: "Fear Release",
    description: "Gently release the intensity of fear responses and restore calm.",
    durationMinutes: 7,
    difficulty: "beginner",
    script: {
      sessionId: "phobias-fear-release",
      title: "Fear Release",
      estimatedDurationMinutes: 7,
      rounds: [
        makeRound(1, "setup", "Even though I feel this intense fear, I accept myself as I am.", [
          "Even though this fear feels overwhelming",
          "This terror that grips my body",
          "My heart is racing with fear",
          "I feel frozen and afraid",
          "This fear feels out of proportion",
          "I know it logically, but my body reacts",
          "This automatic fear response",
          "The dread that takes over",
          "I accept myself with this fear",
        ]),
        makeRound(2, "tapping", "I am gently calming my fear response.", [
          "Gently calming this fear",
          "My body is learning it's safe",
          "This fear response is softening",
          "I can breathe through this",
          "My nervous system is settling",
          "The intensity is reducing",
          "I am safe in this moment",
          "My body is relaxing now",
          "Fear is releasing its grip",
        ], true, true),
        makeRound(3, "positive_reframe", "I face what I fear with growing courage.", [
          "I am safe and grounded",
          "My courage is growing",
          "I face fears at my own pace",
          "I am more than my fears",
          "My body knows how to be calm",
          "I trust myself to handle this",
          "Each time gets a little easier",
          "I am brave and resilient",
          "Peace replaces fear",
        ]),
      ],
    },
  },
  {
    id: "phobias-social-anxiety",
    categoryId: "phobias",
    title: "Social Anxiety Relief",
    description: "Ease the discomfort of social situations and build social confidence.",
    durationMinutes: 7,
    difficulty: "beginner",
    script: {
      sessionId: "phobias-social-anxiety",
      title: "Social Anxiety Relief",
      estimatedDurationMinutes: 7,
      rounds: [
        makeRound(1, "setup", "Even though I feel anxious around others, I accept myself completely.", [
          "Even though I feel so anxious around people",
          "This fear of being judged",
          "What if they think I'm awkward",
          "This self-consciousness that paralyzes me",
          "I just want to disappear",
          "This knot in my stomach before social events",
          "The dread of small talk",
          "This feeling of not belonging",
          "I accept myself with all this anxiety",
        ]),
        makeRound(2, "tapping", "I am releasing social anxiety.", [
          "Letting go of this social fear",
          "I don't need everyone's approval",
          "Most people are focused on themselves",
          "I can be imperfect and still be liked",
          "Releasing the pressure to perform",
          "I can just be myself",
          "My nervousness is softening",
          "Social situations are getting easier",
          "I belong just as I am",
        ], true),
        makeRound(3, "positive_reframe", "I am comfortable being myself around others.", [
          "I am at ease around others",
          "People enjoy my company",
          "I bring value just by being me",
          "I connect authentically with others",
          "Social situations flow naturally",
          "I am confident in who I am",
          "I release the need to be perfect",
          "I enjoy connecting with people",
          "I am socially confident and calm",
        ]),
      ],
    },
  },
  {
    id: "phobias-facing-unknown",
    categoryId: "phobias",
    title: "Facing the Unknown",
    description: "Process fears of uncertainty, heights, enclosed spaces, and general phobic responses.",
    durationMinutes: 8,
    difficulty: "intermediate",
    script: {
      sessionId: "phobias-facing-unknown",
      title: "Facing the Unknown",
      estimatedDurationMinutes: 8,
      rounds: [
        makeRound(1, "setup", "Even though the unknown terrifies me, I choose to trust myself through it.", [
          "Even though this situation terrifies me",
          "This intense fear of what might happen",
          "My body goes into panic mode",
          "I feel trapped by this fear",
          "This irrational response I can't control",
          "The what-ifs that spiral in my mind",
          "This feeling of losing control",
          "My body remembers the fear",
          "I accept myself and this response",
        ]),
        makeRound(2, "tapping", "I am reprogramming my fear response.", [
          "Gently rewiring this fear",
          "My brain can learn new responses",
          "This fear was trying to protect me",
          "I thank it and release it",
          "I am safe to face this gradually",
          "My nervous system is learning",
          "The old response is fading",
          "New calm pathways are forming",
          "I am in control of my response",
        ], true, true),
        makeRound(3, "positive_reframe", "I move through fear with calm and confidence.", [
          "I face challenges with courage",
          "I am larger than my fears",
          "Each step forward builds confidence",
          "I trust my ability to cope",
          "I am calm in new situations",
          "My bravery inspires me",
          "I embrace the unknown with curiosity",
          "I am free from old fear patterns",
          "I am courageous and capable",
        ]),
      ],
    },
  },

  // Chronic Pain
  {
    id: "chronic-pain-ease",
    categoryId: "chronic-pain",
    title: "Pain Ease",
    description: "Ease the emotional weight of chronic pain. Complementary to medical treatment, not a substitute.",
    durationMinutes: 7,
    difficulty: "beginner",
    script: {
      sessionId: "chronic-pain-ease",
      title: "Pain Ease",
      estimatedDurationMinutes: 7,
      rounds: [
        makeRound(1, "setup", "Even though I'm in pain, I accept myself and my body as we are.", [
          "Even though this pain won't go away",
          "This constant aching in my body",
          "I'm so tired of hurting",
          "This pain that follows me everywhere",
          "The frustration of living with pain",
          "My body feels like it's betraying me",
          "This exhaustion from managing pain",
          "The grief of what pain has taken",
          "I accept myself and my body right now",
        ]),
        makeRound(2, "tapping", "I am easing the emotional weight of this pain.", [
          "Releasing the emotional layer of this pain",
          "My body deserves compassion",
          "I can soften around the pain",
          "Breathing ease into tight places",
          "The emotional tension is releasing",
          "I separate pain from suffering",
          "My body is doing its best",
          "I send kindness to the places that hurt",
          "The emotional grip is loosening",
        ], true),
        makeRound(3, "positive_reframe", "I hold my body with compassion and care.", [
          "I am more than my pain",
          "My body deserves gentle care",
          "I find moments of ease throughout my day",
          "Comfort flows to where I need it",
          "I am resilient and strong",
          "I focus on what my body can do",
          "Each breath brings a little relief",
          "I treat myself with tenderness",
          "I am at peace with my body today",
        ]),
      ],
    },
  },
  {
    id: "chronic-pain-body-acceptance",
    categoryId: "chronic-pain",
    title: "Body Acceptance",
    description: "Heal your relationship with a body in pain. Complementary to medical treatment, not a substitute.",
    durationMinutes: 8,
    difficulty: "intermediate",
    script: {
      sessionId: "chronic-pain-body-acceptance",
      title: "Body Acceptance",
      estimatedDurationMinutes: 8,
      rounds: [
        makeRound(1, "setup", "Even though I struggle with my body, I choose to make peace with it.", [
          "Even though I'm angry at my body",
          "This body that doesn't work the way I want",
          "I feel betrayed by my own body",
          "The resentment I carry toward my pain",
          "Missing who I was before the pain",
          "This body that limits me",
          "The frustration of not being believed",
          "Feeling broken and defeated",
          "I accept these feelings about my body",
        ]),
        makeRound(2, "tapping", "I am making peace with my body.", [
          "Releasing anger toward my body",
          "My body is not the enemy",
          "We're on the same team",
          "I can be frustrated and still be kind",
          "My body is fighting for me every day",
          "I release the need for my old body",
          "I honor what my body does for me",
          "Compassion is replacing resentment",
          "I am making friends with my body again",
        ], true, true),
        makeRound(3, "positive_reframe", "I honor and accept my body as it is today.", [
          "I accept my body as it is today",
          "My body is worthy of love",
          "I appreciate what still works",
          "I am gentle with my limitations",
          "My worth is not defined by my pain",
          "I honor my body's wisdom",
          "I am whole, even in pain",
          "I choose compassion over frustration",
          "I am at peace with my body",
        ]),
      ],
    },
  },
  {
    id: "chronic-pain-gentle-release",
    categoryId: "chronic-pain",
    title: "Gentle Release",
    description: "A soft, meditative session to release stored tension. Complementary to medical treatment, not a substitute.",
    durationMinutes: 8,
    difficulty: "beginner",
    script: {
      sessionId: "chronic-pain-gentle-release",
      title: "Gentle Release",
      estimatedDurationMinutes: 8,
      rounds: [
        makeRound(1, "setup", "Even though my body holds tension and pain, I choose gentleness.", [
          "Even though my body is tense and tight",
          "This tension I've been holding",
          "My muscles are bracing against pain",
          "This guarding that exhausts me",
          "My body is in protective mode",
          "The stiffness that won't release",
          "Holding tension for so long",
          "My body has forgotten how to relax",
          "I accept this tension with compassion",
        ]),
        makeRound(2, "tapping", "I am inviting my body to soften and release.", [
          "Inviting my body to soften",
          "It's safe to let go a little",
          "Gentle release in my shoulders",
          "Softening wherever I can",
          "My body has permission to relax",
          "Breathing into the tight spots",
          "Slowly unwinding the tension",
          "My body remembers how to be soft",
          "Release flows through me naturally",
        ], true),
        makeRound(3, "positive_reframe", "My body knows how to find ease and comfort.", [
          "My body knows how to heal",
          "Softness and ease are available to me",
          "I melt into comfort",
          "My body releases what it no longer needs",
          "I am relaxed and at ease",
          "Comfort wraps around me",
          "I trust my body's ability to find ease",
          "Each breath deepens my relaxation",
          "I rest in gentle peace",
        ]),
      ],
    },
  },
];

export function getSessionsByCategory(categoryId: string): PreBuiltSession[] {
  return PRE_BUILT_SESSIONS.filter((s) => s.categoryId === categoryId);
}

export function getSessionById(id: string): PreBuiltSession | undefined {
  return PRE_BUILT_SESSIONS.find((s) => s.id === id);
}
